insert into `articulos` (`descripcion`, `id`, `precio`, `stock`) values ('Harina Royal - 1 KG', 1, '1.99', 100);
insert into `articulos` (`descripcion`, `id`, `precio`, `stock`) values ('Vino Casillero del Diablo - 1 LT', 2, '7.99', 200);
insert into `articulos` (`descripcion`, `id`, `precio`, `stock`) values ('Manjar de Leche Soprole - 1 KG', 3, '2.99', 90);
insert into `articulos` (`descripcion`, `id`, `precio`, `stock`) values ('Azucar - 5 KG', 4, '2.99', 170);
insert into `articulos` (`descripcion`, `id`, `precio`, `stock`) values ('Queso Colun - 500 GR', 5, '4.99', 70);
insert into `articulos` (`descripcion`, `id`, `precio`, `stock`) values ('Cerveza Austral - 750 ML', 6, '5.99', 120);
insert into `articulos` (`descripcion`, `id`, `precio`, `stock`) values ('Aceitunas Negras - 1/4 KG', 7, '3.99', 200);
insert into `articulos` (`descripcion`, `id`, `precio`, `stock`) values ('Carne Lomo Liso - 2 KG', 8, '30.00', 187);
insert into `articulos` (`descripcion`, `id`, `precio`, `stock`) values ('Mani Salado Acuenta - 1 KG', 9, '5.99', 80);
insert into `articulos` (`descripcion`, `id`, `precio`, `stock`) values ('Cerveza Royal - 750 CC', 10, '2.99', 73);
;